from metodos.EcuacionesDeUnaVariable.MetodosPorIntervalos.busquedasIncrementales import *
from metodos.EcuacionesDeUnaVariable.MetodosPorIntervalos.metodoBiseccion import *
from metodos.EcuacionesDeUnaVariable.MetodosPorIntervalos.reglafalsa import *
