from metodos.SistemasDeEcuaciones.MetodosDeEliminacion.eliminacionGaussianaSimple import *
from metodos.SistemasDeEcuaciones.MetodosDeEliminacion.eliminacionGaussianaPivoteoParcial import *
from metodos.SistemasDeEcuaciones.MetodosDeEliminacion.EliminacionGaussianaPivoteoTotal import *